import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
const { chromium } = await import(process.env.OLYMPUS_QA_PLAYWRIGHT ?? 'playwright');
const base = process.env.OLYMPUS_NATIVE_QA_URL;
if (!base || !['127.0.0.1', 'localhost', '[::1]'].includes(new URL(base).hostname)) throw new Error('A disposable loopback OLYMPUS_NATIVE_QA_URL is required');
const output = process.env.OLYMPUS_QA_OUTPUT;
if (!output) throw new Error('OLYMPUS_QA_OUTPUT must name the disposable artifact directory');
await mkdir(output, {recursive:true});
const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
const context = await browser.newContext({viewport:{width:1280,height:900},permissions:['clipboard-read','clipboard-write']});
const page = await context.newPage();
page.setDefaultTimeout(7000);
const errors=[]; page.on('pageerror',e=>errors.push(String(e)));
const evidence={};
async function paste(text) {
  return page.locator('textarea[placeholder]').evaluate((el,text)=>{
    const data=new DataTransfer();data.setData('text/plain',text);
    const e=new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:data});el.dispatchEvent(e);return e.defaultPrevented;
  },text);
}
try {
 await page.goto(base+'/tasks/new');
 const composer=page.locator('textarea[placeholder]'); await composer.fill('Existing instruction');
 const text='Clipboard document <script>window.pasteExecuted=true</script> 😀\r\n'+Array.from({length:55},(_,i)=>'Unicode line '+i+' — é 🚀').join('\n');
 const upload=page.waitForResponse(r=>r.url().includes('/api/files/upload')&&r.request().method()==='POST');
 assert.equal(await paste(text),true);
 const uploaded=await (await upload).json(); evidence.upload=uploaded;
 assert.equal(await composer.inputValue(),'Existing instruction');
 await page.getByText('56 lines').waitFor();
 await page.getByRole('link',{name:'Preview pasted text'}).waitFor();
 const pop=page.waitForEvent('popup'); await page.getByRole('link',{name:'Preview pasted text'}).click();
 const preview=await pop;await preview.waitForLoadState();
 assert.equal(await preview.evaluate(()=>fetch(location.href).then(r=>r.text())),text,'text preview preserves original UTF-8 and CRLF');
 assert.equal(await preview.evaluate(()=>!!window.pasteExecuted),false,'pasted HTML remains inert plain text');
 await preview.close();evidence.preview=true;
 await page.screenshot({path:join(output,'qa-paste-desktop.png'),fullPage:true});
 await page.setViewportSize({width:320,height:800});
 evidence.pasteOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 const controls=await page.getByRole('button',{name:'Keep inline'}).evaluate(el=>{const box=el.getBoundingClientRect();return {left:box.left,right:box.right,width:innerWidth}});
 assert.ok(controls.left>=0&&controls.right<=controls.width,'paste actions must fit without being clipped by overflow-hidden ancestors: '+JSON.stringify(controls));
 await page.screenshot({path:join(output,'qa-paste-mobile.png'),fullPage:true});
 await page.getByRole('button',{name:'Keep inline'}).click();
 assert.equal(await composer.inputValue(),'Existing instruction'+text.replace(/\r\n/g,'\n'), 'HTML textareas normalize line endings; file bytes remain original');
 assert.equal(await page.getByRole('button',{name:'Keep inline'}).count(),0);
 await composer.fill('small ');await composer.focus();
 await page.evaluate(()=>navigator.clipboard.writeText('paste'));await composer.press('Control+V');
 assert.equal(await composer.inputValue(),'small paste');
 evidence.paste=true;
 await page.setViewportSize({width:1280,height:1000});
 const response=await page.request.post(base+'/api/tasks',{data:{title:'Native question form QA',description:'Disposable native interaction and attachment checks.'}});
 assert.equal(response.status(),201); const {task}=await response.json(); const id=task.id;
 evidence.taskId=id;
 await page.goto(base+'/tasks/'+id);
 await page.locator('textarea[placeholder]').fill('Ask task scope, checks, and constraints using the native question tool.');
 await page.locator('textarea[placeholder]').press('Enter');
 await page.getByText('Hermes is waiting for you.',{exact:true}).waitFor({timeout:45000});
 const initial=await (await page.request.get(`${base}/api/tasks/${id}/interactions`)).json();evidence.interactionId=initial.interactions[0].id;
 await page.reload();await page.getByText('Hermes is waiting for you.',{exact:true}).waitFor();
 const after=await (await page.request.get(`${base}/api/tasks/${id}/interactions`)).json();assert.equal(after.interactions[0].id,evidence.interactionId);
 const submit=page.getByRole('button',{name:'Submit answers'});assert.equal(await submit.isDisabled(),true);
 await page.getByRole('radio',{name:/^Core only/}).check();
 await page.getByRole('checkbox',{name:/^Tests/}).check();
 const many=page.locator('fieldset').nth(1); const other=many.locator('input[type="checkbox"]').last();
 await other.check(); assert.equal(await other.isChecked(),true,'Other can be selected before typing');
 await many.locator('input[type="text"]').fill('First custom value');
 await many.locator('input[type="text"]').fill('Updated custom value');
 await page.locator('fieldset').nth(2).locator('textarea').fill('No deployment. Preserve exact answers.');
 await page.screenshot({path:join(output,'qa-form-desktop.png'),fullPage:true});
 await page.setViewportSize({width:320,height:900});
 evidence.formOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 await page.screenshot({path:join(output,'qa-form-mobile.png'),fullPage:true});
 assert.equal(await submit.isEnabled(),true);
 await submit.click();
 await page.getByText('QA fixture received the task answers:',{exact:false}).waitFor({timeout:30000});
 const settled=await (await page.request.get(`${base}/api/tasks/${id}/interactions`)).json();const form=settled.interactions.find(i=>i.id===evidence.interactionId);
 assert.equal(form.status,'answered');assert.ok(form.response);assert.ok(Object.values(form.response.answers).some(v=>Array.isArray(v)&&v.includes('Updated custom value')));
 assert.ok(!JSON.stringify(form.response).includes('First custom value'));
 const replay=await page.request.post(`${base}/api/tasks/${id}/interactions/${form.id}/respond`,{data:{workerRunId:form.workerRunId,response:form.response}});assert.equal(replay.status(),409);
 evidence.form=true;
 // Persist a paste through the existing-task composer, then reload and download the actual stored document.
 await page.setViewportSize({width:1280,height:1000});
 await page.locator('textarea[placeholder]').fill('Retain this attachment for the task.');
 const persistedUpload=page.waitForResponse(r=>r.url().includes('/api/files/upload')&&r.request().method()==='POST');
 await paste(text);await persistedUpload;
 await page.getByRole('button',{name:'Send message',exact:true}).waitFor();
 await page.getByRole('button',{name:'Send message',exact:true}).click();
 await page.getByText('Hermes is waiting for you.',{exact:true}).waitFor({timeout:30000});
 await page.reload();await page.getByText('Hermes is waiting for you.',{exact:true}).waitFor();
 const card=page.getByRole('link',{name:/clipboard-paste\.txt/});await card.waitFor();
 const downloadUrl=await card.getAttribute('href');const downloaded=await page.request.get(new URL(downloadUrl,base).href);
 assert.equal(downloaded.status(),200);assert.equal(await downloaded.text(),text,'persisted task attachment bytes round-trip exactly');
 evidence.persistedPaste=true;
 // Stopping a pending native form closes the prompt and must not mark this run successful.
 const stop=await page.request.post(`${base}/api/tasks/${id}/interrupt`,{data:{}});assert.equal(stop.status(),200);
 await page.getByText('This request was closed when the run stopped.',{exact:true}).waitFor({timeout:15000});
 const closed=await (await page.request.get(`${base}/api/tasks/${id}/interactions`)).json();
 assert.ok(!closed.interactions.some(i=>i.status==='waiting'||i.status==='claimed'));
 const finalTask=await (await page.request.get(`${base}/api/tasks/${id}`)).json();assert.equal(finalTask.task.status,'in_progress','unanswered stopped run stays retryable');
 evidence.stop=true;
 // Upload failure/retry/removal and complete New Task creation are real UI paths.
 await page.goto(base+'/tasks/new'); await page.locator('textarea[placeholder]').fill('New task with a document.');
 let failOnce=true;
 await page.route('**/api/files/upload**', async route=>{
   if (failOnce) {failOnce=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Injected QA upload failure'})});}
   else await route.continue();
 });
 await paste(text); const retry=page.getByRole('button',{name:'Retry clipboard-paste.txt'});await retry.waitFor();
 assert.equal(await page.locator('textarea[placeholder]').inputValue(),'New task with a document.');
 const retryUpload=page.waitForResponse(r=>r.url().includes('/api/files/upload')&&r.request().method()==='POST');
 await retry.click();assert.equal((await retryUpload).ok(),true);await retry.waitFor({state:'hidden'});
 await page.unroute('**/api/files/upload**');
 await page.getByRole('button',{name:'Remove clipboard-paste.txt'}).click();
 assert.equal(await page.getByRole('button',{name:'Keep inline'}).count(),0);
 const newUpload=page.waitForResponse(r=>r.url().includes('/api/files/upload')&&r.request().method()==='POST');
 await paste(text);await newUpload;
 await page.getByRole('button',{name:'Send message',exact:true}).waitFor();
 await page.getByRole('button',{name:'Send message',exact:true}).click();
 await page.waitForURL(/\/tasks\/(?!new)[^/]+$/);
 await page.getByText('Hermes is waiting for you.',{exact:true}).waitFor({timeout:30000});
 const newId=new URL(page.url()).pathname.split('/').pop();await page.reload();
 const newCard=page.getByRole('link',{name:/clipboard-paste\.txt/});await newCard.waitFor();
 const newDownload=await page.request.get(new URL(await newCard.getAttribute('href'),base).href);
 assert.equal(newDownload.status(),200);assert.equal(await newDownload.text(),text);
 await page.request.post(`${base}/api/tasks/${newId}/interrupt`,{data:{}});
 evidence.newTaskPaste=true;evidence.failedUploadRetryRemove=true;
 evidence.errors=errors;assert.deepEqual(errors,[]);
 assert.equal(evidence.pasteOverflow,false,'paste chip fits 320px');assert.equal(evidence.formOverflow,false,'form fits 320px');
 await writeFile(join(output,'evidence.json'),JSON.stringify(evidence,null,2));
 console.log('BROWSER_FEATURES_PASS',JSON.stringify(evidence));
} catch(e) { console.log('BROWSER_FEATURES_FAIL',JSON.stringify(evidence),String(e));await page.screenshot({path:join(output,'qa-failure.png'),fullPage:true});process.exitCode=1; }
finally {await browser.close();}
