import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const root = await mkdtemp(join(tmpdir(), 'coding-evidence-'));
process.env.DB_PATH = join(root, 'db.sqlite'); process.env.OLYMPUS_DISPATCH_HOME = join(root, 'state');
const { default: db } = await import('../server/db/index.js');
const { insertTask } = await import('../server/db/queries.js');
const { captureCodingBaseline, verifyCodingRun, readCodingEvidence } = await import('../server/coding-verification.js');
const cwd = join(root, 'repo'); await mkdir(join(cwd, '.olympus'), { recursive: true });
const git = (...args: string[]) => promisify(execFile)('git', args, { cwd });
try {
 await git('init'); await git('config', 'user.email', 'test@example.invalid'); await git('config', 'user.name', 'Test');
 await writeFile(join(cwd, 'source.txt'), 'before'); await git('add', '.'); await git('commit', '-m', 'baseline');
 const task = insertTask({ title: 'Coding task', status: 'in_progress', workdir: cwd });
 await captureCodingBaseline(task, 'run');
 await writeFile(join(cwd, '.olympus/verification.json'), JSON.stringify({ commands: [[process.execPath, '-e', 'console.log("checked")']] }));
 await writeFile(join(cwd, 'source.txt'), 'after');
 assert.equal(await verifyCodingRun(task, 'run', 2000), true);
 let evidence = await readCodingEvidence(task);
 assert.equal(evidence?.status, 'passed'); assert.equal(evidence?.checks[0]?.exitCode, 0); assert.match(evidence?.checks[0]?.output ?? '', /checked/);
 await writeFile(join(cwd, 'source.txt'), 'after more edits');
 evidence = await readCodingEvidence(task); assert.equal(evidence?.status, 'stale', 'same HEAD does not mean same source');
 await writeFile(join(cwd, '.olympus/verification.json'), JSON.stringify({ commands: [[process.execPath, '-e', 'process.exit(1)']] }));
 assert.equal(await verifyCodingRun(task, 'run', 2000), false);
 assert.equal((await readCodingEvidence(task))?.status, 'failed');
 await writeFile(join(cwd, '.olympus/verification.json'), JSON.stringify({ commands: [[process.execPath, '-e', 'setInterval(()=>{},1000)']] }));
 const at = Date.now(); assert.equal(await verifyCodingRun(task, 'run', 50), false); assert.ok(Date.now() - at < 1500);
 await writeFile(join(cwd, '.olympus/verification.json'), JSON.stringify({ commands: [[process.execPath, '-e', 'require("fs").writeFileSync("source.txt","mutated during check")']] }));
 assert.equal(await verifyCodingRun(task, 'run', 2000), false, 'checks that modify source cannot attest the original source');
 await mkdir(join(cwd, 'client'));
 const nested = insertTask({ title: 'Nested coding task', status: 'in_progress', workdir: join(cwd, 'client') });
 await writeFile(join(cwd, '.olympus/verification.json'), JSON.stringify({ commands: [[process.execPath, '-e', 'process.exit(1)']] }));
 await captureCodingBaseline(nested, 'nested');
 assert.equal(await verifyCodingRun(nested, 'nested', 2000), false, 'nested workdirs must use repository verification');
 await git('add', '.'); await git('commit', '-m', 'committed failing source');
 assert.equal(await verifyCodingRun(task, 'run', 2000), false);
 assert.match((await readCodingEvidence(task))?.source?.diff ?? '', /mutated during check/, 'committed changes remain in the run diff');
 await captureCodingBaseline(task, 'noop');
 assert.equal(await verifyCodingRun(task, 'noop', 2000), false, 'a no-op turn must not bypass failed checks on committed source');
} finally { db.close(); await rm(root, { recursive: true, force: true }); }
console.log('Coding verification tests passed');
