import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const root = await mkdtemp(join(tmpdir(), 'goal-contract-'));
process.env.HERMES_HOME = join(root, 'hermes');
process.env.OLYMPUS_DISPATCH_HOME = join(root, 'olympus');
process.env.DB_PATH = join(root, 'state.db');
process.env.OLYMPUS_CHAT_MAX_RUN_MS = '150';
process.env.OLYMPUS_CHAT_IDLE_TIMEOUT_MS = '100';
await mkdir(process.env.HERMES_HOME, { recursive: true });
await writeFile(join(process.env.HERMES_HOME, 'config.yaml'), '{}\n');
const { default: app, adapter } = await import('../server/app.js');
const { default: db } = await import('../server/db/index.js');
const { insertTask, getTask } = await import('../server/db/queries.js');
const { getLatestTaskAgentRun } = await import('../server/db/task-agent-runs.js');
const { discardRun } = await import('../server/live-chat.js');
const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
const api = `http://127.0.0.1:${(server.address() as { port: number }).port}/api/tasks`;
const ids: string[] = [];
adapter.getBackgroundWork = async () => ({ available: true, work: [] });
adapter.setGoal = async () => ({ goal: 'unfinished', status: 'active', turnsUsed: 0, maxTurns: 20 });
adapter.chatStream = async function* (sessionId) { yield { type: 'text_delta', content: 'More work remains.' }; yield { type: 'done', sessionId }; };
adapter.interruptChat = async () => true;
const post = async (id: string) => fetch(`${api}/${id}/messages?profile=default`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content: 'Finish the goal', settings: { mode: 'goal' } }) });
const wait = async (id: string) => { for (let i = 0; i < 100 && getLatestTaskAgentRun(id)?.status === 'streaming'; i++) await new Promise(r => setTimeout(r, 5)); };
try {
  const cap = insertTask({ title: 'Goal cap', status: 'in_progress', profile_name: 'default' }); ids.push(cap.id);
  let turns = 0;
  adapter.evaluateGoal = async () => ++turns <= 22
    ? { status: 'active', shouldContinue: true, verdict: 'continue', reason: 'unfinished', message: '', continuationPrompt: 'Continue' }
    : { status: 'done', shouldContinue: false, verdict: 'done', reason: 'finished', message: '' };
  assert.equal((await post(cap.id)).status, 202); await wait(cap.id);
  assert.equal(getLatestTaskAgentRun(cap.id)?.status, 'done', 'only native Hermes decides when the goal stops');
  assert.equal(turns, 23);
  assert.equal(getTask(cap.id)?.status, 'in_review');
  const stalled = insertTask({ title: 'Stalled evaluation', status: 'in_progress', profile_name: 'default' }); ids.push(stalled.id);
  adapter.evaluateGoal = async () => { await new Promise(r => setTimeout(r, 200)); return { status: 'done', shouldContinue: false, verdict: 'done', reason: 'finished', message: '' }; };
  assert.equal((await post(stalled.id)).status, 202); await wait(stalled.id);
  assert.equal(getLatestTaskAgentRun(stalled.id)?.status, 'done', 'quiet evaluation outlives legacy runtime cap');
  const inactive = insertTask({ title: 'Paused goal', status: 'in_progress', profile_name: 'default' }); ids.push(inactive.id);
  adapter.evaluateGoal = async () => ({ status: 'paused', shouldContinue: false, verdict: 'inactive', reason: 'paused', message: '' });
  assert.equal((await post(inactive.id)).status, 202); await wait(inactive.id);
  assert.notEqual(getLatestTaskAgentRun(inactive.id)?.status, 'done');
  process.env.OLYMPUS_CHAT_MAX_RUN_MS = '5000';
  const stopped = insertTask({ title: 'Stopped evaluation', status: 'in_progress', profile_name: 'default' }); ids.push(stopped.id);
  adapter.evaluateGoal = () => new Promise(() => {});
  assert.equal((await post(stopped.id)).status, 202);
  await new Promise(r => setTimeout(r, 20));
  assert.equal((await fetch(`${api}/${stopped.id}/interrupt`, { method: 'POST' })).status, 200);
  await wait(stopped.id);
  assert.equal(getLatestTaskAgentRun(stopped.id)?.status, 'stopped', 'stop must promptly settle a stalled evaluation');
  process.env.OLYMPUS_CHAT_MAX_RUN_MS = '150';
  const setup = insertTask({ title: 'Stalled setup', status: 'in_progress', profile_name: 'default' }); ids.push(setup.id);
  adapter.setGoal = async () => { await new Promise(r => setTimeout(r, 200)); return { goal: 'objective', status: 'active', turnsUsed: 0, maxTurns: 20 }; };
  adapter.evaluateGoal = async () => ({ status: 'done', shouldContinue: false, verdict: 'done', reason: 'finished', message: '' });
  const result = await Promise.race([post(setup.id), new Promise<never>((_, reject) => setTimeout(() => reject(new Error('setup escaped deadline')), 500))]);
  assert.equal(result.status, 202);
  await wait(setup.id);
  assert.equal(getLatestTaskAgentRun(setup.id)?.status, 'done');
} finally {
  for (const id of ids) discardRun(id);
  server.close(); await once(server, 'close'); db.close(); await rm(root, { recursive: true, force: true });
}
console.log('Goal completion contract tests passed');
