import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const app = await readFile('client/src/App.tsx', 'utf8');
const sidebar = await readFile('client/src/components/Sidebar.tsx', 'utf8');
const header = await readFile('client/src/components/Header.tsx', 'utf8');
const projects = await readFile('client/src/components/ProjectsPage.tsx', 'utf8').catch(() => '');
const detail = await readFile('client/src/components/ProjectDetailPage.tsx', 'utf8').catch(() => '');
const newTask = await readFile('client/src/components/NewTaskPage.tsx', 'utf8');
const api = await readFile('client/src/lib/api.ts', 'utf8');
const settings = await readFile('client/src/components/SettingsPage.tsx', 'utf8');
const githubSettings = await readFile('client/src/components/GitHubSettings.tsx', 'utf8');
const studio = await readFile('client/src/components/StudioProjectsPage.tsx', 'utf8');

assert.match(app, /path="\/projects" element=\{<ProjectsPage \/>\}/);
assert.match(app, /path="\/projects\/:projectId" element=\{<ProjectDetailPage \/>\}/);
assert.match(app, /path="\/projects\/:projectId\/tasks\/:taskId" element=\{<TaskDetailPage \/>\}/);
assert.match(sidebar, /label="Projects"[\s\S]*to="\/projects"/);
assert.match(header, /isProjects/);
assert.match(header, /parentTitle = 'Projects'/);
assert.match(header, /parentTo = '\/projects'/);
assert.match(projects, /Projects/);
assert.match(projects, /New Project/);
assert.match(projects, /Managed by/);
assert.match(projects, /Purpose/);
assert.match(projects, /manager\.provider/);
assert.match(projects, /manager\.model/);
assert.match(detail, /Manager history/);
assert.match(detail, /Edit Project/);
assert.match(detail, /Previous owner keeps/);
assert.match(detail, /Collaborators/);
assert.match(detail, /setProjectGrant/);
assert.match(detail, /revokeProjectGrant/);
assert.match(detail, /New task/);
assert.match(detail, /References/);
assert.match(detail, /uploadProjectReference/);
assert.match(detail, /uploadState/);
assert.match(detail, /Indexing/);
assert.match(detail, /fetchProjectReferences/);
assert.match(detail, /searchProjectReferences/);
assert.match(detail, /reindexProjectReference/);
assert.match(detail, /deleteProjectReference/);
assert.match(detail, /Project reference search/);
assert.match(api, /export function uploadProjectReference\(/);
assert.match(api, /export function fetchProjectReferences\(/);
assert.match(api, /export function searchProjectReferences\(/);
assert.match(api, /export function projectReferenceDownloadUrl\(/);
assert.match(detail, /Repository/);
assert.match(detail, /repositoryLink/);
assert.match(detail, /fetchStudioGitHubStatus/);
assert.match(detail, />Code</);
assert.match(detail, /Commit & Push/);
assert.match(detail, /protected branch/);
assert.doesNotMatch(detail, /read-only/);
assert.match(detail, /Version history/);
assert.match(detail, /Revert to this version/);
assert.match(detail, /acquireProjectEditor/);
assert.match(detail, /releaseProjectEditor/);
assert.match(api, /export function fetchProjectVersions\(/);
assert.match(api, /export function fetchProjectEditor\(/);
assert.match(api, /export function acquireProjectEditor\(/);
assert.match(api, /export function commitPushProject\(/);
assert.match(api, /export function revertProjectVersion\(/);
assert.match(projects, /GitHub connection \(optional\)/);
assert.match(projects, /selectableStudioRepositories/);
assert.match(settings, /GitHubSettings/);
assert.match(githubSettings, /GitHub connections/);
assert.match(githubSettings, /Credentials are managed only here/);
assert.match(studio, /Navigate to="\/settings#github" replace/);
assert.match(newTask, /aria-label="Project"/);
assert.match(newTask, /No project/);
assert.doesNotMatch(newTask, /Location\s*<select/);
assert.doesNotMatch(newTask, /<option value="">Inbox<\/option>/);
assert.match(newTask, /aria-label="Profile"/);
assert.doesNotMatch(newTask, /Handled by/);
assert.doesNotMatch(newTask, /ProjectFolderPicker/);
assert.match(newTask, /max-w-4xl/);
assert.match(newTask, /flex-wrap/);
assert.match(newTask, /Future tasks use the Project manager policy/);
assert.match(api, /export function fetchProjects\(/);
assert.match(api, /export function createProject\(/);
assert.match(api, /export function fetchProject\(/);
assert.match(api, /export function fetchProjectTasks\(/);
assert.match(api, /export function updateProject\(/);
assert.match(api, /export function fetchProjectRepositoryLink\(/);
assert.match(api, /export function upsertProjectRepositoryLink\(/);
assert.match(api, /export function deleteProjectRepositoryLink\(/);
assert.match(api, /export function fetchProjectGrants\(/);
assert.match(api, /export function setProjectGrant\(/);
assert.match(api, /export function revokeProjectGrant\(/);
assert.match(api, /projectId/);
assert.match(api, /handlingProfileId/);

console.log('Global Projects and task-location UI tests passed');
