import assert from 'node:assert/strict';
import { createAgentRouter } from '../server/routes/agent.js';
let received: unknown[] = [];
const router = createAgentRouter({ manageProviders: async (...args: unknown[]) => { received = args; return { providers: [] }; } } as never);
const route = router.stack.find(layer => layer.route?.path === '/providers' && layer.route.methods.post)?.route;
assert.ok(route, 'provider management API must exist');
const handle = route.stack.at(-1)!.handle;
let body: unknown; let status = 200;
const response = { set: () => response, json: (value: unknown) => { body = value; }, status: (value: number) => { status = value; return response; } };
await handle({ activeHermesProfile: { id: 'som' }, body: { action: 'discover', baseUrl: 'https://api.example/v1', apiKey: 'write-only', extra: 'never-forward' } } as never, response as never, () => {});
assert.deepEqual(received, [{ action: 'discover', baseUrl: 'https://api.example/v1', apiKey: 'write-only' }, 'som']);
assert.deepEqual(body, { providers: [] });
received = [];
await handle({ body: { action: 'unknown', apiKey: 'private' } } as never, response as never, () => {});
assert.equal(status, 400); assert.deepEqual(received, []); assert.doesNotMatch(JSON.stringify(body), /private/);
const failing = createAgentRouter({ manageProviders: async () => { throw new Error('Bearer private'); } } as never);
const failedHandle = failing.stack.find(layer => layer.route?.path === '/providers' && layer.route.methods.post)!.route!.stack.at(-1)!.handle;
await failedHandle({ activeHermesProfile: { id: 'som' }, body: { action: 'list' } } as never, response as never, () => {});
assert.equal(status, 503); assert.doesNotMatch(JSON.stringify(body), /private/);
console.log('Provider configuration routing and secret redaction passed');
