import assert from 'node:assert/strict';
Object.defineProperty(globalThis, 'localStorage', { value: { getItem: () => null, setItem: () => {} }, configurable: true });
const { useStore, reconcilePersistedTaskRun } = await import('../client/src/lib/store.js');
const run = { taskId: 'task', runId: 'one', kind: 'chat' as const, status: 'streaming' as const, startedAt: 100, updatedAt: 100 };
useStore.getState().setTaskRun(run);
reconcilePersistedTaskRun({ ...run, status: 'error', updatedAt: 200 });
assert.equal(useStore.getState().taskRuns.has('task'), false, 'terminal history clears stale board/composer streaming state');
useStore.getState().setTaskRun({ ...run, runId: 'two', startedAt: 300, updatedAt: 300 });
reconcilePersistedTaskRun({ ...run, status: 'error', updatedAt: 200 });
assert.equal(useStore.getState().taskRuns.get('task')?.runId, 'two', 'old history cannot clear a newer run');
console.log('Reconnect run store tests passed');
useStore.getState().setTaskRuns([]);
useStore.getState().setTaskRuns([{ ...run, status: 'error', recoveryState: 'blocked' }]);
assert.equal(useStore.getState().taskOutcomes.get('task')?.status, 'error', 'reload retains a failed outcome without marking it active');
assert.equal(useStore.getState().taskRuns.size, 0);
useStore.getState().setTaskRun({ ...run, status: 'error', recoveryState: 'pending' });
assert.equal(useStore.getState().taskOutcomes.get('task')?.recoveryState, 'pending');
useStore.getState().setTaskRun({ ...run, runId: 'new', startedAt: 500 });
assert.equal(useStore.getState().taskOutcomes.has('task'), false, 'new active run clears the old failure');
useStore.getState().setTaskRun({ ...run, status: 'error', recoveryState: 'blocked' });
assert.equal(useStore.getState().taskRuns.get('task')?.runId, 'new', 'late old recovery cannot replace newer execution');
assert.equal(useStore.getState().taskOutcomes.has('task'), false);
useStore.getState().setTaskRuns([{ ...run, status: 'error', recoveryState: 'blocked' }]);
assert.equal(useStore.getState().taskRuns.get('task')?.runId, 'new', 'delayed snapshot cannot replace a newer active run');
useStore.getState().setTaskRun({ ...run, runId: 'new', startedAt: 500, status: 'error', recoveryState: 'blocked' });
useStore.getState().setTaskRuns([{ ...run, runId: 'new', startedAt: 500, status: 'streaming' }]);
assert.equal(useStore.getState().taskOutcomes.get('task')?.status, 'error', 'same-run stale streaming snapshot cannot revive terminal execution');
