import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const app = await readFile('server/app.ts', 'utf8');
const clientApp = await readFile('client/src/App.tsx', 'utf8');
const settings = await readFile('client/src/components/SettingsPage.tsx', 'utf8');
const githubSettings = await readFile('client/src/components/GitHubSettings.tsx', 'utf8');
const api = await readFile('client/src/lib/api.ts', 'utf8');
const page = await readFile('client/src/components/StudioProjectsPage.tsx', 'utf8');

assert.match(app, /const studioGitHubGateway = createGitHubAppGateway\(\{ credentialStore: createGitHubCredentialStore\(\) \}\);/);
assert.match(app, /app\.use\('\/api\/studio', createStudioRouter\(\{[\s\S]*github: studioGitHubGateway,[\s\S]*publicUrl: process\.env\.OLYMPUS_STUDIO_PUBLIC_URL/);
assert.match(clientApp, /path="\/studio" element=\{<StudioProjectsPage \/>\}/);
assert.match(settings, /<GitHubSettings \/>/);
assert.match(api, /export function connectStudioGitHub\(owner: string \| null\)/);
assert.match(api, /export function updateStudioGitHubInstallation\(installationId: number, label: string\)/);
assert.match(api, /export function deleteStudioGitHubInstallation\(installationId: number\)/);
assert.match(api, /JSON\.stringify\(\{ owner \}\)/);
assert.match(api, /method: 'GET' \| 'POST'/);
assert.match(api, /fields: Record<string, string>/);
assert.match(api, /export function fetchStudioRepositories\(installationId: number\)/);
assert.match(api, /export function importStudioProject\(installationId: number, repositoryId: number\)/);
assert.match(githubSettings, /Git providers/);
assert.match(githubSettings, /GitHub/);
assert.match(githubSettings, /Personal account/);
assert.match(githubSettings, /Organization/);
assert.match(githubSettings, /Organization handle/);
assert.match(githubSettings, /useState<'' \| 'personal' \| 'organization'>\(''\)/);
assert.match(githubSettings, /<option value="">Select owner type<\/option>/);
assert.match(githubSettings, /disabled=\{working \|\| !githubOwnerType \|\| \(githubOwnerType === 'organization' && !validOrganizationHandle\)\}/);
assert.match(githubSettings, /Connect GitHub account/);
assert.match(githubSettings, /Add GitHub account/);
assert.match(githubSettings, /Read & write/);
assert.match(githubSettings, /Manage on GitHub/);
assert.match(githubSettings, /Edit connection/);
assert.match(githubSettings, /Delete connection/);
assert.match(githubSettings, /Disconnect account/);
assert.match(githubSettings, /Upgrade permissions/);
assert.match(githubSettings, /Continue with GitHub/);
assert.match(githubSettings, /connectStudioGitHub\(\s*githubOwnerType === 'organization' \? organizationHandle\.trim\(\) : null,?\s*\)/);
assert.match(githubSettings, /document\.createElement\('form'\)/);
assert.match(githubSettings, /form\.method = 'POST'/);
assert.match(githubSettings, /form\.submit\(\)/);
assert.match(githubSettings, /create branches, commit, and push/);
assert.match(githubSettings, /Credentials are managed only here/);
assert.match(page, /Navigate to="\/settings#github" replace/);
assert.doesNotMatch(githubSettings, /Configure the Studio GitHub App ID, slug, private key, client ID, and client secret/);
assert.doesNotMatch(githubSettings, /Add project/);
assert.doesNotMatch(githubSettings, /read-only GitHub App installations/);
assert.doesNotMatch(githubSettings, /Deploy production|Merge to main|Push to main/);

console.log('Studio Settings GitHub onboarding UI tests passed');
