import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const app = await readFile('server/app.ts', 'utf8');
const clientApp = await readFile('client/src/App.tsx', 'utf8');
const sidebar = await readFile('client/src/components/Sidebar.tsx', 'utf8');
const api = await readFile('client/src/lib/api.ts', 'utf8');
const page = await readFile('client/src/components/StudioProjectsPage.tsx', 'utf8');

assert.match(app, /app\.use\('\/api\/studio', createStudioRouter\(\{[\s\S]*github: createGitHubAppGateway\(\{ credentialStore: createGitHubCredentialStore\(\) \}\),[\s\S]*publicUrl: process\.env\.OLYMPUS_STUDIO_PUBLIC_URL/);
assert.match(clientApp, /path="\/studio" element=\{<StudioProjectsPage \/>\}/);
assert.match(sidebar, /label="Projects"[\s\S]*to="\/projects"/);
assert.match(api, /export function connectStudioGitHub\(owner: string \| null\)/);
assert.match(api, /JSON\.stringify\(\{ owner \}\)/);
assert.match(api, /method: 'GET' \| 'POST'/);
assert.match(api, /fields: Record<string, string>/);
assert.match(api, /export function fetchStudioRepositories\(installationId: number\)/);
assert.match(api, /export function importStudioProject\(installationId: number, repositoryId: number\)/);
assert.match(page, /Connect GitHub/);
assert.match(page, /Personal account/);
assert.match(page, /Organization/);
assert.match(page, /Organization handle/);
assert.match(page, /useState<'' \| 'personal' \| 'organization'>\(''\)/);
assert.match(page, /<option value="">Select owner type<\/option>/);
assert.match(page, /disabled=\{working \|\| !githubOwnerType \|\| \(githubOwnerType === 'organization' && !validOrganizationHandle\)\}/);
assert.match(page, /Connect another GitHub account/);
assert.match(page, /Continue with GitHub/);
assert.match(page, /connectStudioGitHub\(\s*githubOwnerType === 'organization' \? organizationHandle\.trim\(\) : null,?\s*\)/);
assert.match(page, /document\.createElement\('form'\)/);
assert.match(page, /form\.method = 'POST'/);
assert.match(page, /form\.submit\(\)/);
assert.match(page, /Choose which repositories Olympus can access/);
assert.match(page, /You can revoke access at any time/);
assert.doesNotMatch(page, /disabled=\{!configured \|\| working\}/);
assert.doesNotMatch(page, /Configure the Studio GitHub App ID, slug, private key, client ID, and client secret/);
assert.match(page, /Add project/);
assert.doesNotMatch(page, /approve.*repository/i);
assert.match(page, /Read-only/);
assert.doesNotMatch(page, /Deploy production|Merge to main|Push to main/);

console.log('Studio Projects route and read-only onboarding UI tests passed');
