import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { StreamEvent } from '../server/adapters/types.js';
const root = await mkdtemp(join(tmpdir(),'reliability-routes-'));
process.env.HERMES_HOME = join(root,'hermes');
process.env.OLYMPUS_DISPATCH_HOME = join(root,'olympus');
process.env.DB_PATH = join(root,'state.db');
await mkdir(process.env.HERMES_HOME,{recursive:true});
await writeFile(join(process.env.HERMES_HOME,'config.yaml'),'{}\n');
const { default:app, adapter } = await import('../server/app.js');
const { default:db } = await import('../server/db/index.js');
const { insertTask, getTask } = await import('../server/db/queries.js');
const { createTaskAgentRun, finishTaskAgentRun, getLatestTaskAgentRun } = await import('../server/db/task-agent-runs.js');
const { getQueuedTaskMessage } = await import('../server/db/task-message-queue.js');
const { discardRun, getRun } = await import('../server/live-chat.js');
const server=app.listen(0,'127.0.0.1'); await once(server,'listening');
const port=(server.address() as {port:number}).port;
const api=`http://127.0.0.1:${port}/api/tasks`;
const originals={chat:adapter.chatStream,background:adapter.getBackgroundWork,stop:adapter.stopBackgroundWork,page:adapter.getMessagePage};
adapter.getMessagePage=async()=>({messages:[],pageInfo:{hasOlder:false,olderCursor:null}});
let started=0;
adapter.chatStream=async function*(sessionId):AsyncIterable<StreamEvent>{started++;yield {type:'text_delta',content:'Partial work'};yield {type:'error',error:'Runtime cap',code:'run_runtime_timeout'};yield {type:'done',sessionId};};
const post=(id:string,body:unknown)=>fetch(`${api}/${id}/messages?profile=default`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const tasks:string[]=[];
try {
 const task=insertTask({title:'Failed work',status:'in_progress',profile_name:'default'});tasks.push(task.id);
 createTaskAgentRun({runId:'prior',taskId:task.id,kind:'chat',status:'streaming',startedAt:1});finishTaskAgentRun('prior','error',2,'run_runtime_timeout');
 const queued={id:'pending-followup',content:'Continue implementation',settings:{mode:'task'},invitedProfileIds:[],collaborationScope:'discussion',confirmPersistentCollaboration:false};
 assert.equal((await fetch(`${api}/${task.id}/queued-message?profile=default`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(queued)})).status,200);
 adapter.getBackgroundWork=async()=>({available:true,work:[{id:'proc-owned',kind:'process',status:'running'}]});
 const legacy=insertTask({title:'Legacy interrupted task',status:'in_progress',profile_name:'default'});tasks.push(legacy.id);
 assert.equal((await post(legacy.id,{content:'Retry older task'})).status,409,'missing durable run row must not bypass inventory');
 assert.equal(started,0);
 let response=await post(task.id,{content:queued.content,queuedMessageId:queued.id});
 assert.equal(response.status,409,'surviving task-owned work prevents duplicate execution');
 assert.equal((await response.json()).code,'BACKGROUND_WORK_ACTIVE');assert.equal(started,0);
 assert.equal(getQueuedTaskMessage(task.id)?.id,queued.id,'preflight rejection does not consume queued input');

 // An idle task exposes recovery, but only for the exact work the user saw.
 const inspect=()=>fetch(`${api}/${task.id}/background-work?profile=default`);
 const stop=(body:unknown)=>fetch(`${api}/${task.id}/background-work/stop?profile=default`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 let stopped=0;
 adapter.stopBackgroundWork=async(id,ids)=>{assert.equal(id,task.id);assert.deepEqual(ids,['proc-owned']);stopped++;return {available:true,work:[]};};
 let background=await inspect();
 assert.equal(background.status,200,'idle background work must be recoverable in the UI');
 const snapshot=await background.json();
 assert.equal(snapshot.canStop,true);assert.equal(snapshot.runId,'prior');
 assert.equal((await stop({runId:'stale',processIds:['proc-owned']})).status,409);
 assert.equal((await stop({runId:'prior',processIds:['other-process']})).status,409);
 assert.equal(stopped,0,'stale tabs and arbitrary process IDs must never stop work');
 adapter.getBackgroundWork=async()=>({available:true,work:[{id:'proc-owned',kind:'process',status:'running'},{id:'child',kind:'delegation',status:'running'}]});
 assert.equal((await (await inspect()).json()).canStop,false);
 assert.equal((await stop({runId:'prior',processIds:['proc-owned']})).status,409);
 assert.equal(stopped,0,'active delegated work must not be interrupted');
 const { claimTaskOperation }=await import('../server/task-run-lifecycle.js');
 const release=claimTaskOperation(task.id)!;
 try {assert.equal((await stop({runId:'prior',processIds:['proc-owned']})).status,409);} finally {release();}
 adapter.getBackgroundWork=async()=>({available:true,work:[{id:'proc-owned',kind:'process',status:'running'}]});
 assert.equal((await stop({runId:'prior',processIds:['proc-owned']})).status,200);
 assert.equal(stopped,1);
 assert.equal(getTask(task.id)?.status,'in_progress','cleanup must not mark unfinished work as reviewed');
 assert.equal(getQueuedTaskMessage(task.id)?.id,queued.id,'cleanup preserves the queued follow-up');
 // A disconnected browser cannot release the Project while cleanup still runs.
 const { createProject }=await import('../server/db/projects.js');
 const { claimProjectOperation, hasTaskOperation }=await import('../server/task-run-lifecycle.js');
 const project=createProject({name:'Cleanup ownership',purpose:'Test cleanup',managerProfileId:'default',changedBy:'test'});
 db.prepare('UPDATE tasks SET project_id = ? WHERE id = ?').run(project.id,task.id);
 assert.equal(getTask(task.id)?.project_id,project.id);
 let entered!:()=>void; let finish!:()=>void;
 const enteredPromise=new Promise<void>(resolve=>{entered=resolve;});
 const pendingCleanup=new Promise<void>(resolve=>{finish=resolve;});
 adapter.stopBackgroundWork=async()=>{entered();await pendingCleanup;return {available:true,work:[]};};
 const abort=new AbortController();
 const disconnected=fetch(`${api}/${task.id}/background-work/stop?profile=default`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({runId:'prior',processIds:['proc-owned']}),signal:abort.signal}).catch(()=>undefined);
 try {
  await enteredPromise;abort.abort();await disconnected;
  const competing=claimProjectOperation(project.id);
  try {assert.equal(competing,null,'Project cannot transfer while cleanup is still running');} finally {competing?.();}
 } finally {finish();}
 for(let i=0;i<100 && hasTaskOperation(task.id);i++) await new Promise(resolve=>setTimeout(resolve,5));
 assert.equal(hasTaskOperation(task.id),false,'cleanup completion releases ownership');
 db.prepare('UPDATE tasks SET project_id = NULL WHERE id = ?').run(task.id);
 const foreign=insertTask({title:'Other profile',status:'in_progress',profile_name:'other'});tasks.push(foreign.id);
 assert.equal((await fetch(`${api}/${foreign.id}/background-work?profile=default`)).status,404);
 assert.equal((await fetch(`${api}/${foreign.id}/background-work/stop?profile=default`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({runId:null,processIds:['proc-owned']})})).status,404);
 adapter.getBackgroundWork=async()=>({available:false,work:[]});
 response=await post(task.id,{content:queued.content,queuedMessageId:queued.id});
 assert.equal(response.status,503,'unavailable inventory fails closed');assert.equal(started,0);
 adapter.getBackgroundWork=async()=>({available:true,work:[]});
 response=await post(task.id,{content:queued.content,queuedMessageId:queued.id});
 assert.equal(response.status,202,await response.text());
 for(let i=0;i<30 && getLatestTaskAgentRun(task.id)?.status==='streaming';i++) await new Promise(r=>setTimeout(r,5));
 assert.equal(started,1);assert.equal(getTask(task.id)?.status,'in_progress','error plus done is not review-ready');
 assert.equal(getLatestTaskAgentRun(task.id)?.errorCode,'run_runtime_timeout');
 assert.equal(getRun(task.id)?.status,'error');
 discardRun(task.id);
 const page=await (await fetch(`${api}/${task.id}/messages?profile=default`)).json();
 assert.equal(page.latestAgentRun.errorCode,'run_runtime_timeout','reload after snapshot expiry retains reason');
 // A stream that just ends after a checkpoint is also incomplete, never synthesized success.
 const partial=insertTask({title:'Unexpected EOF',status:'in_progress',profile_name:'default'});tasks.push(partial.id);
 adapter.chatStream=async function*(){yield {type:'text_delta',content:'Still working'};};
 assert.equal((await post(partial.id,{content:'Build task'})).status,202);
 for(let i=0;i<30 && getLatestTaskAgentRun(partial.id)?.status==='streaming';i++) await new Promise(r=>setTimeout(r,5));
 assert.equal(getTask(partial.id)?.status,'in_progress');assert.equal(getLatestTaskAgentRun(partial.id)?.status,'error');
 assert.equal(getLatestTaskAgentRun(partial.id)?.errorCode,'stream_incomplete');
} finally {adapter.chatStream=originals.chat;adapter.getBackgroundWork=originals.background;adapter.stopBackgroundWork=originals.stop;adapter.getMessagePage=originals.page;for(const id of tasks)discardRun(id);server.close();await once(server,'close');db.close();await rm(root,{recursive:true,force:true});}
console.log('Task recovery route tests passed');
