import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { StreamEvent } from '../server/adapters/types.js';
const root = await mkdtemp(join(tmpdir(),'reliability-routes-'));
process.env.HERMES_HOME = join(root,'hermes');
process.env.OLYMPUS_DISPATCH_HOME = join(root,'olympus');
process.env.DB_PATH = join(root,'state.db');
await mkdir(process.env.HERMES_HOME,{recursive:true});
await writeFile(join(process.env.HERMES_HOME,'config.yaml'),'{}\n');
const { default:app, adapter } = await import('../server/app.js');
const { default:db } = await import('../server/db/index.js');
const { insertTask, getTask } = await import('../server/db/queries.js');
const { createTaskAgentRun, finishTaskAgentRun, getLatestTaskAgentRun } = await import('../server/db/task-agent-runs.js');
const { getQueuedTaskMessage } = await import('../server/db/task-message-queue.js');
const { discardRun, getRun } = await import('../server/live-chat.js');
const server=app.listen(0,'127.0.0.1'); await once(server,'listening');
const port=(server.address() as {port:number}).port;
const api=`http://127.0.0.1:${port}/api/tasks`;
const originals={chat:adapter.chatStream,background:adapter.getBackgroundWork,page:adapter.getMessagePage};
adapter.getMessagePage=async()=>({messages:[],pageInfo:{hasOlder:false,olderCursor:null}});
let started=0;
adapter.chatStream=async function*(sessionId):AsyncIterable<StreamEvent>{started++;yield {type:'text_delta',content:'Partial work'};yield {type:'error',error:'Runtime cap',code:'run_runtime_timeout'};yield {type:'done',sessionId};};
const post=(id:string,body:unknown)=>fetch(`${api}/${id}/messages?profile=default`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const tasks:string[]=[];
try {
 const task=insertTask({title:'Failed work',status:'in_progress',profile_name:'default'});tasks.push(task.id);
 createTaskAgentRun({runId:'prior',taskId:task.id,kind:'chat',status:'streaming',startedAt:1});finishTaskAgentRun('prior','error',2,'run_runtime_timeout');
 const queued={id:'pending-followup',content:'Continue implementation',settings:{mode:'task'},invitedProfileIds:[],collaborationScope:'discussion',confirmPersistentCollaboration:false};
 assert.equal((await fetch(`${api}/${task.id}/queued-message?profile=default`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(queued)})).status,200);
 adapter.getBackgroundWork=async()=>({available:true,work:[{id:'proc-owned',kind:'process',status:'running'}]});
 let response=await post(task.id,{content:queued.content,queuedMessageId:queued.id});
 assert.equal(response.status,409,'surviving task-owned work prevents duplicate execution');
 assert.equal((await response.json()).code,'BACKGROUND_WORK_ACTIVE');assert.equal(started,0);
 assert.equal(getQueuedTaskMessage(task.id)?.id,queued.id,'preflight rejection does not consume queued input');
 adapter.getBackgroundWork=async()=>({available:false,work:[]});
 response=await post(task.id,{content:queued.content,queuedMessageId:queued.id});
 assert.equal(response.status,503,'unavailable inventory fails closed');assert.equal(started,0);
 adapter.getBackgroundWork=async()=>({available:true,work:[]});
 response=await post(task.id,{content:queued.content,queuedMessageId:queued.id});
 assert.equal(response.status,202,await response.text());
 for(let i=0;i<30 && getLatestTaskAgentRun(task.id)?.status==='streaming';i++) await new Promise(r=>setTimeout(r,5));
 assert.equal(started,1);assert.equal(getTask(task.id)?.status,'in_progress','error plus done is not review-ready');
 assert.equal(getLatestTaskAgentRun(task.id)?.errorCode,'run_runtime_timeout');
 assert.equal(getRun(task.id)?.status,'error');
 discardRun(task.id);
 const page=await (await fetch(`${api}/${task.id}/messages?profile=default`)).json();
 assert.equal(page.latestAgentRun.errorCode,'run_runtime_timeout','reload after snapshot expiry retains reason');
 // A stream that just ends after a checkpoint is also incomplete, never synthesized success.
 const partial=insertTask({title:'Unexpected EOF',status:'in_progress',profile_name:'default'});tasks.push(partial.id);
 adapter.chatStream=async function*(){yield {type:'text_delta',content:'Still working'};};
 assert.equal((await post(partial.id,{content:'Build task'})).status,202);
 for(let i=0;i<30 && getLatestTaskAgentRun(partial.id)?.status==='streaming';i++) await new Promise(r=>setTimeout(r,5));
 assert.equal(getTask(partial.id)?.status,'in_progress');assert.equal(getLatestTaskAgentRun(partial.id)?.status,'error');
 assert.equal(getLatestTaskAgentRun(partial.id)?.errorCode,'stream_incomplete');
} finally {adapter.chatStream=originals.chat;adapter.getBackgroundWork=originals.background;adapter.getMessagePage=originals.page;for(const id of tasks)discardRun(id);server.close();await once(server,'close');db.close();await rm(root,{recursive:true,force:true});}
console.log('Task recovery route tests passed');
