// Disposable UI fixture: all Hermes/state/repository paths are created in tmpdir.
import { once } from 'node:events';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import express from 'express';
const root = await mkdtemp(join(tmpdir(), 'olympus-060-browser-'));
process.env.HERMES_HOME = join(root, 'hermes');
process.env.OLYMPUS_DISPATCH_HOME = join(root, 'state');
process.env.DB_PATH = join(root, 'state.db');
await mkdir(process.env.HERMES_HOME, { recursive: true });
await writeFile(join(process.env.HERMES_HOME, 'config.yaml'), '{}\n');
const { default: app, adapter } = await import('../../server/app.js');
const { default: db } = await import('../../server/db/index.js');
const { insertTask } = await import('../../server/db/queries.js');
const { createTaskAgentRun, finishTaskAgentRun } = await import('../../server/db/task-agent-runs.js');
const { captureCodingBaseline, verifyCodingRun } = await import('../../server/coding-verification.js');
const { beginRecovery, recoveryOutcome, saveRecoveryCheckpoint } = await import('../../server/run-recovery.js');
const { startRun, discardRun, closeSubscribersForTasks } = await import('../../server/live-chat.js');
const defaults = { model: 'gpt-5.5', provider: 'openai-codex', reasoningEffort: 'xhigh' as const, baseUrl: null, apiMode: null, showReasoning: true };
adapter.healthCheck = async () => true;
adapter.getDefaults = async () => defaults;
adapter.getModels = async () => ({ defaultModel: defaults.model, activeProvider: defaults.provider, groups: [{ provider: defaults.provider, models: [{ id: defaults.model, label: 'GPT-5.5', source: 'current' }] }] });
adapter.getSessionMetadata = async () => null;
adapter.getBackgroundWork = async () => ({ available: true, work: [], continuation: { status: 'pending' } });
const cwd = join(root, 'repo'); await mkdir(join(cwd, '.olympus'), { recursive: true });
const git = (...args: string[]) => promisify(execFile)('git', args, { cwd });
await git('init'); await git('config', 'user.name', 'Isolated QA'); await git('config', 'user.email', 'qa@example.invalid');
await writeFile(join(cwd, 'source.txt'), 'before\n'); await git('add', '.'); await git('commit', '-m', 'baseline');
const task = insertTask({ title: 'Verify source changes before review', status: 'in_progress', profile_name: 'default', workdir: cwd });
const runId = 'browser-code-run';
createTaskAgentRun({ taskId: task.id, runId, kind: 'chat', status: 'streaming', startedAt: Date.now() });
await captureCodingBaseline(task, runId);
await writeFile(join(cwd, 'source.txt'), 'after\n');
await writeFile(join(cwd, '.olympus/verification.json'), JSON.stringify({ commands: [[process.execPath, '-e', 'console.log("Required check failed: expected green");process.exit(1)']] }));
await verifyCodingRun(task, runId); finishTaskAgentRun(runId, 'done', Date.now());
const reconnect = insertTask({ title: 'Recover after a missed terminal event', status: 'in_progress', profile_name: 'default' });
const started = startRun(reconnect.id, reconnect.id, 'Continue the release');
createTaskAgentRun({ taskId: reconnect.id, runId: started.snapshot.runId, kind: 'chat', status: 'streaming', startedAt: started.snapshot.startedAt });
beginRecovery(reconnect.id, started.snapshot.runId, started.snapshot.startedAt);
adapter.getMessagePage = async (_sessionId, taskId) => ({ messages: [{ id: `${taskId}-reply`, task_id: taskId, role: 'assistant', content: taskId === task.id ? 'Implemented the source change. A required check still fails.' : 'Saved partial response before the connection was lost.', created_at: Date.now() - 1000 }], pageInfo: { hasOlder: false, olderCursor: null } });
app.post('/qa/checks-pass', async (_req, res) => { await writeFile(join(cwd, '.olympus/verification.json'), JSON.stringify({ commands: [[process.execPath, '-e', 'console.log("All required checks passed")']] })); res.json({ ok: true }); });
app.post('/qa/change-source', async (_req, res) => { await writeFile(join(cwd, 'source.txt'), 'changed after verification\n'); res.json({ ok: true }); });
app.post('/qa/expire-stream', (_req, res) => {
  finishTaskAgentRun(started.snapshot.runId, 'error', Date.now(), 'worker_restarted');
  recoveryOutcome(reconnect.id, started.snapshot.runId, 'error', 'worker_restarted');
  saveRecoveryCheckpoint(reconnect.id, started.snapshot.runId, { saved: true, source: 'task-continuation-journal' });
  discardRun(reconnect.id); closeSubscribersForTasks([reconnect.id]); res.json({ ok: true });
});
const dist = resolve('dist/server/client/dist'); app.use(express.static(dist)); app.get(/.*/, (_req, res) => res.sendFile(join(dist, 'index.html')));
const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
const port = (server.address() as { port: number }).port;
console.log(JSON.stringify({ coding: `http://127.0.0.1:${port}/tasks/${task.id}?profile=default`, reconnect: `http://127.0.0.1:${port}/tasks/${reconnect.id}?profile=default`, root }));
process.on('SIGTERM', () => { server.closeAllConnections(); server.close(() => { db.close(); void rm(root, { recursive: true, force: true }).then(() => process.exit()); }); });
